apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvc-deployment
spec:
  selector:
    matchLabels:
      app: mvc
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mvc
    spec:
      containers:
      - name: mvc
        image: pradeepsvs25/mycrud:v1.1
        ports:
        - containerPort: 80
        env:
          - name: ConnectionStrings__ProductsContext        
            valueFrom:
              secretKeyRef:
                name:  mssql-secret
                key: db-connection-string                
              # configMapKeyRef:
              #   name: mssql-connection-configmap
              #   key: db-connection-string
--- 
apiVersion: v1
kind: Service
metadata:
  name: mvc-service
spec:
  selector:
    app: mvc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80      
  type: LoadBalancer    